export const UPPERCASE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
export const LOWERCASE = 'abcdefghijklmnopqrstuvwxyz'
export const NUMBERS = '0123456789'
export const SYMBOLS = '!@#$%^&*()_+-=[]{}|;:,.<>?'
export const SIMILAR = '0Oo1lI'
